name: easy_coffee_copy_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  flutter_polyline_points: ^0.2.6
  google_maps_flutter: ^2.0.2
  geolocator: ^9.0.1
  awesome_snackbar_content: ^0.0.8
  flutter_google_places: ^0.3.0
  google_api_headers: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
